server:
  port: 8089

file:
  dir: ${user.dir}/src/main/resources/files/

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shieldusdb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true

 # 파일 업로드 크기 설정
  servlet:
    multipart:
      max-file-size: 1000MB
