server:
  port: 8089

file:
  dir: ${user.dir}/src/main/resources/files/

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shieldusdb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        # 서버 시작 시마다 DB 초기화
        show-sql: true
        format_sql: true

    hibernate:
      ddl-auto: create


 # 파일 업로드 크기 설정
  servlet:
    multipart:
      max-file-size: 10000MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
